<?php
/**
 * Governed content surface registry.
 *
 * @package TailwindScore
 */

declare(strict_types=1);

defined( 'ABSPATH' ) || exit;

/**
 * Registry definitions for all supported content surfaces.
 *
 * @return array<string, array<string, mixed>>
 */
function tailwindscore_content_surface_registry(): array {
	static $registry = null;

	if ( null !== $registry ) {
		return $registry;
	}

	$registry = array(
		'announcement-bar-message' => array(
			'key'                 => 'announcement-bar-message',
			'label'               => 'Announcement bar message',
			'fallback'            => __( 'Complimentary shipping on domestic orders over $150.', 'tailwindscore' ),
			'mood_surface'        => 'announcement_language',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_site_shell_announcement_text',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_announcement_bar_message',
				'group'      => 'content_surfaces',
				'section'    => 'site_shell',
				'control'    => 'text',
			),
		),
		'footer-brand-summary'    => array(
			'key'                 => 'footer-brand-summary',
			'label'               => 'Footer brand summary',
			'fallback'            => __( 'Editorial commerce foundation for a calm, premium shopping journey.', 'tailwindscore' ),
			'mood_surface'        => 'footer_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_textarea',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_site_shell_footer_summary',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_footer_brand_summary',
				'group'      => 'content_surfaces',
				'section'    => 'footer',
				'control'    => 'textarea',
			),
		),
		'footer-legal-notice'     => array(
			'key'                 => 'footer-legal-notice',
			'label'               => 'Footer legal notice',
			'fallback'            => __( 'Copyright %s. All rights reserved.', 'tailwindscore' ),
			'mood_surface'        => 'footer_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_site_shell_footer_legal_text',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_footer_legal_notice',
				'group'      => 'content_surfaces',
				'section'    => 'footer',
				'control'    => 'text',
			),
		),
		'footer-newsletter-copy'  => array(
			'key'                 => 'footer-newsletter-copy',
			'label'               => 'Footer newsletter copy',
			'fallback'            => __( 'Use this surface for a concise editorial newsletter invitation, not a marketing wall of text.', 'tailwindscore' ),
			'mood_surface'        => 'newsletter_prompts',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_textarea',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_footer_newsletter_copy',
				'group'      => 'content_surfaces',
				'section'    => 'footer',
				'control'    => 'textarea',
			),
		),
		'support-message'         => array(
			'key'                 => 'support-message',
			'label'               => 'Support message',
			'fallback'            => __( 'Support information should stay concise, reassuring, and close to purchase-critical guidance.', 'tailwindscore' ),
			'mood_surface'        => 'support_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_textarea',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_site_shell_support_message',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_support_message',
				'group'      => 'content_surfaces',
				'section'    => 'footer',
				'control'    => 'textarea',
			),
		),
		'guarantee-text'          => array(
			'key'                 => 'guarantee-text',
			'label'               => 'Guarantee text',
			'fallback'            => __( 'Guarantee copy belongs in one governed surface so trust language stays consistent across commerce touchpoints.', 'tailwindscore' ),
			'mood_surface'        => 'trust_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_textarea',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_guarantee_text',
				'group'      => 'content_surfaces',
				'section'    => 'commerce',
				'control'    => 'textarea',
			),
		),
		'trust-message'           => array(
			'key'                 => 'trust-message',
			'label'               => 'Trust message',
			'fallback'            => __( 'Trust messaging should clarify shipping, returns, and confidence signals without fragmenting into per-component copy fields.', 'tailwindscore' ),
			'mood_surface'        => 'trust_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_textarea',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_trust_message',
				'group'      => 'content_surfaces',
				'section'    => 'commerce',
				'control'    => 'textarea',
			),
		),
		'footer-social-links'     => array(
			'key'                 => 'footer-social-links',
			'label'               => 'Footer social links',
			'fallback'            => array(),
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_social_links',
			'translation_support' => false,
			'ssr_output'          => 'tailwindscore_site_shell_social_links',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_footer_social_links',
				'group'      => 'content_surfaces',
				'section'    => 'footer',
				'control'    => 'repeater',
			),
		),
		'checkout-payment-guidance-message' => array(
			'key'                 => 'checkout-payment-guidance-message',
			'label'               => 'Checkout payment guidance message',
			'fallback'            => __( 'Choose a payment method and complete the order with one clear confirmation.', 'tailwindscore' ),
			'mood_surface'        => 'checkout_reassurance',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_textarea',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_checkout_payment_guidance_message',
				'group'      => 'content_surfaces',
				'section'    => 'checkout',
				'control'    => 'textarea',
			),
		),
		'checkout-mobile-summary-message' => array(
			'key'                 => 'checkout-mobile-summary-message',
			'label'               => 'Checkout mobile summary message',
			'fallback'            => __( 'Shipping, taxes, and discounts stay visible before purchase completion.', 'tailwindscore' ),
			'mood_surface'        => 'checkout_reassurance',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_textarea',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_checkout_mobile_summary_message',
				'group'      => 'content_surfaces',
				'section'    => 'checkout',
				'control'    => 'textarea',
			),
		),
		'checkout-validation-summary-message' => array(
			'key'                 => 'checkout-validation-summary-message',
			'label'               => 'Checkout validation summary message',
			'fallback'            => __( 'Please review the highlighted checkout details.', 'tailwindscore' ),
			'mood_surface'        => 'checkout_reassurance',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_checkout_validation_summary_message',
				'group'      => 'content_surfaces',
				'section'    => 'checkout',
				'control'    => 'text',
			),
		),
		'checkout-validation-title' => array(
			'key'                 => 'checkout-validation-title',
			'label'               => 'Checkout validation title',
			'fallback'            => __( 'Please review your checkout details', 'tailwindscore' ),
			'mood_surface'        => 'checkout_reassurance',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_checkout_validation_title',
				'group'      => 'content_surfaces',
				'section'    => 'checkout',
				'control'    => 'text',
			),
		),
		'checkout-loading-message' => array(
			'key'                 => 'checkout-loading-message',
			'label'               => 'Checkout loading message',
			'fallback'            => __( 'Updating checkout', 'tailwindscore' ),
			'mood_surface'        => 'checkout_reassurance',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_checkout_loading_message',
				'group'      => 'content_surfaces',
				'section'    => 'checkout',
				'control'    => 'text',
			),
		),
		'checkout-layout-title' => array(
			'key'                 => 'checkout-layout-title',
			'label'               => 'Checkout layout title',
			'fallback'            => __( 'Checkout', 'tailwindscore' ),
			'mood_surface'        => 'checkout_reassurance',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_checkout_layout_title',
				'group'      => 'content_surfaces',
				'section'    => 'checkout',
				'control'    => 'text',
			),
		),
		'checkout-summary-subtotal-label' => array(
			'key'                 => 'checkout-summary-subtotal-label',
			'label'               => 'Checkout summary subtotal label',
			'fallback'            => __( 'Subtotal', 'tailwindscore' ),
			'mood_surface'        => 'checkout_reassurance',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_checkout_summary_subtotal_label',
				'group'      => 'content_surfaces',
				'section'    => 'checkout',
				'control'    => 'text',
			),
		),
		'account-dashboard-message' => array(
			'key'                 => 'account-dashboard-message',
			'label'               => 'Account dashboard message',
			'fallback'            => __( 'Orders, addresses, downloads, and account details arranged in one calm post-purchase space.', 'tailwindscore' ),
			'mood_surface'        => 'account_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_textarea',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_account_dashboard_message',
				'group'      => 'content_surfaces',
				'section'    => 'account',
				'control'    => 'textarea',
			),
		),
		'account-orders-message' => array(
			'key'                 => 'account-orders-message',
			'label'               => 'Account orders message',
			'fallback'            => __( 'Track each purchase, reopen details when needed, and keep your post-purchase history easy to scan.', 'tailwindscore' ),
			'mood_surface'        => 'account_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_textarea',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_account_orders_message',
				'group'      => 'content_surfaces',
				'section'    => 'account',
				'control'    => 'textarea',
			),
		),
		'account-view-order-message' => array(
			'key'                 => 'account-view-order-message',
			'label'               => 'Account view order message',
			'fallback'            => __( 'A clear summary of status, items, totals, and delivery information without dashboard clutter.', 'tailwindscore' ),
			'mood_surface'        => 'account_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_textarea',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_account_view_order_message',
				'group'      => 'content_surfaces',
				'section'    => 'account',
				'control'    => 'textarea',
			),
		),
		'account-downloads-message' => array(
			'key'                 => 'account-downloads-message',
			'label'               => 'Account downloads message',
			'fallback'            => __( 'Keep downloadable products close at hand, with remaining access and expiry details presented quietly.', 'tailwindscore' ),
			'mood_surface'        => 'account_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_textarea',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_account_downloads_message',
				'group'      => 'content_surfaces',
				'section'    => 'account',
				'control'    => 'textarea',
			),
		),
		'account-login-reassurance-message' => array(
			'key'                 => 'account-login-reassurance-message',
			'label'               => 'Account login reassurance message',
			'fallback'            => __( 'Review orders, revisit downloads, and manage saved details from one considered post-purchase surface.', 'tailwindscore' ),
			'mood_surface'        => 'account_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_textarea',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_account_login_reassurance_message',
				'group'      => 'content_surfaces',
				'section'    => 'account',
				'control'    => 'textarea',
			),
		),
		'account-recovery-message' => array(
			'key'                 => 'account-recovery-message',
			'label'               => 'Account recovery message',
			'fallback'            => __( 'Enter the email address used for your account and we will send a reset link with the same measured pacing as the rest of the account experience.', 'tailwindscore' ),
			'mood_surface'        => 'account_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_textarea',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_account_recovery_message',
				'group'      => 'content_surfaces',
				'section'    => 'account',
				'control'    => 'textarea',
			),
		),
		'account-recovery-caption' => array(
			'key'                 => 'account-recovery-caption',
			'label'               => 'Account recovery caption',
			'fallback'            => __( 'Use your account email or username to begin the reset flow.', 'tailwindscore' ),
			'mood_surface'        => 'account_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_textarea',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_account_recovery_caption',
				'group'      => 'content_surfaces',
				'section'    => 'account',
				'control'    => 'textarea',
			),
		),
		'account-reset-message' => array(
			'key'                 => 'account-reset-message',
			'label'               => 'Account reset message',
			'fallback'            => __( 'Create a new password and return to your account without leaving the calm rhythm of the commerce flow.', 'tailwindscore' ),
			'mood_surface'        => 'account_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_textarea',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_account_reset_message',
				'group'      => 'content_surfaces',
				'section'    => 'account',
				'control'    => 'textarea',
			),
		),
		'account-reset-support-message' => array(
			'key'                 => 'account-reset-support-message',
			'label'               => 'Account reset support message',
			'fallback'            => __( 'Choose a password that feels easy to remember and hard to guess.', 'tailwindscore' ),
			'mood_surface'        => 'account_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_textarea',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_account_reset_support_message',
				'group'      => 'content_surfaces',
				'section'    => 'account',
				'control'    => 'textarea',
			),
		),
		'account-address-guidance-message' => array(
			'key'                 => 'account-address-guidance-message',
			'label'               => 'Account address guidance message',
			'fallback'            => __( 'Use the details below for a smoother return to checkout next time.', 'tailwindscore' ),
			'mood_surface'        => 'account_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_textarea',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_account_address_guidance_message',
				'group'      => 'content_surfaces',
				'section'    => 'account',
				'control'    => 'textarea',
			),
		),
		'account-message'         => array(
			'key'                 => 'account-message',
			'label'               => 'Account message',
			'fallback'            => __( 'Account language should feel composed, helpful, and respectful of the customer history it presents.', 'tailwindscore' ),
			'mood_surface'        => 'account_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_textarea',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_account_message',
				'group'      => 'content_surfaces',
				'section'    => 'account',
				'control'    => 'textarea',
			),
		),
		'search-recent-searches-guidance-message' => array(
			'key'                 => 'search-recent-searches-guidance-message',
			'label'               => 'Search recent searches guidance message',
			'fallback'            => __( 'Recent searches remain nearby so returning to a product path feels immediate and quiet.', 'tailwindscore' ),
			'mood_surface'        => 'search_guidance',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_textarea',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_search_recent_searches_guidance_message',
				'group'      => 'content_surfaces',
				'section'    => 'search',
				'control'    => 'textarea',
			),
		),
		'search-eyebrow' => array(
			'key'                 => 'search-eyebrow',
			'label'               => 'Search eyebrow',
			'fallback'            => __( 'Discover', 'tailwindscore' ),
			'mood_surface'        => 'search_guidance',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_search_eyebrow',
				'group'      => 'content_surfaces',
				'section'    => 'search',
				'control'    => 'text',
			),
		),
		'search-title' => array(
			'key'                 => 'search-title',
			'label'               => 'Search title',
			'fallback'            => __( 'Search the collection', 'tailwindscore' ),
			'mood_surface'        => 'search_guidance',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_search_title',
				'group'      => 'content_surfaces',
				'section'    => 'search',
				'control'    => 'text',
			),
		),
		'search-loading-eyebrow' => array(
			'key'                 => 'search-loading-eyebrow',
			'label'               => 'Search loading eyebrow',
			'fallback'            => __( 'Search', 'tailwindscore' ),
			'mood_surface'        => 'search_guidance',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_search_loading_eyebrow',
				'group'      => 'content_surfaces',
				'section'    => 'search',
				'control'    => 'text',
			),
		),
		'search-loading-title' => array(
			'key'                 => 'search-loading-title',
			'label'               => 'Search loading title',
			'fallback'            => __( 'Looking through the collection', 'tailwindscore' ),
			'mood_surface'        => 'search_guidance',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_search_loading_title',
				'group'      => 'content_surfaces',
				'section'    => 'search',
				'control'    => 'text',
			),
		),
		'search-loading-message' => array(
			'key'                 => 'search-loading-message',
			'label'               => 'Search loading message',
			'fallback'            => __( 'A concise set of matching pieces and collection paths is being prepared.', 'tailwindscore' ),
			'mood_surface'        => 'search_guidance',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_textarea',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_search_loading_message',
				'group'      => 'content_surfaces',
				'section'    => 'search',
				'control'    => 'textarea',
			),
		),
		'search-default-state-title' => array(
			'key'                 => 'search-default-state-title',
			'label'               => 'Search default state title',
			'fallback'            => __( 'Begin with a piece, a material, or a collection', 'tailwindscore' ),
			'mood_surface'        => 'search_guidance',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_search_default_state_title',
				'group'      => 'content_surfaces',
				'section'    => 'search',
				'control'    => 'text',
			),
		),
		'search-suggested-searches-heading' => array(
			'key'                 => 'search-suggested-searches-heading',
			'label'               => 'Search suggested searches heading',
			'fallback'            => __( 'Suggested searches', 'tailwindscore' ),
			'mood_surface'        => 'search_guidance',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_search_suggested_searches_heading',
				'group'      => 'content_surfaces',
				'section'    => 'search',
				'control'    => 'text',
			),
		),
		'search-browse-collections-heading' => array(
			'key'                 => 'search-browse-collections-heading',
			'label'               => 'Search browse collections heading',
			'fallback'            => __( 'Browse collections', 'tailwindscore' ),
			'mood_surface'        => 'search_guidance',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_search_browse_collections_heading',
				'group'      => 'content_surfaces',
				'section'    => 'search',
				'control'    => 'text',
			),
		),
		'search-recent-searches-heading' => array(
			'key'                 => 'search-recent-searches-heading',
			'label'               => 'Search recent searches heading',
			'fallback'            => __( 'Recent searches', 'tailwindscore' ),
			'mood_surface'        => 'search_guidance',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_search_recent_searches_heading',
				'group'      => 'content_surfaces',
				'section'    => 'search',
				'control'    => 'text',
			),
		),
		'search-overlay-placeholder' => array(
			'key'                 => 'search-overlay-placeholder',
			'label'               => 'Search overlay placeholder',
			'fallback'            => __( 'Search products, categories, stories', 'tailwindscore' ),
			'mood_surface'        => 'search_guidance',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_search_overlay_placeholder',
				'group'      => 'content_surfaces',
				'section'    => 'search',
				'control'    => 'text',
			),
		),
		'account-secondary-action-label' => array(
			'key'                 => 'account-secondary-action-label',
			'label'               => 'Account secondary action label',
			'fallback'            => __( 'Open', 'tailwindscore' ),
			'mood_surface'        => 'account_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_account_secondary_action_label',
				'group'      => 'content_surfaces',
				'section'    => 'account',
				'control'    => 'text',
			),
		),
		'orders-empty-action-label' => array(
			'key'                 => 'orders-empty-action-label',
			'label'               => 'Orders empty action label',
			'fallback'            => __( 'Browse products', 'tailwindscore' ),
			'mood_surface'        => 'account_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_orders_empty_action_label',
				'group'      => 'content_surfaces',
				'section'    => 'account',
				'control'    => 'text',
			),
		),
		'order-quick-detail-label' => array(
			'key'                 => 'order-quick-detail-label',
			'label'               => 'Order quick detail label',
			'fallback'            => __( 'Quick detail', 'tailwindscore' ),
			'mood_surface'        => 'account_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_order_quick_detail_label',
				'group'      => 'content_surfaces',
				'section'    => 'account',
				'control'    => 'text',
			),
		),
		'view-order-back-label' => array(
			'key'                 => 'view-order-back-label',
			'label'               => 'View order back label',
			'fallback'            => __( 'Back to orders', 'tailwindscore' ),
			'mood_surface'        => 'account_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_view_order_back_label',
				'group'      => 'content_surfaces',
				'section'    => 'account',
				'control'    => 'text',
			),
		),
		'account-edit-account-intro' => array(
			'key'                 => 'account-edit-account-intro',
			'label'               => 'Account edit account intro',
			'fallback'            => __( 'Keep your customer profile current without leaving the post-purchase flow.', 'tailwindscore' ),
			'mood_surface'        => 'account_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_account_edit_account_intro',
				'group'      => 'content_surfaces',
				'section'    => 'account',
				'control'    => 'text',
			),
		),
		'account-login-remember-label' => array(
			'key'                 => 'account-login-remember-label',
			'label'               => 'Account login remember label',
			'fallback'            => __( 'Keep me signed in', 'tailwindscore' ),
			'mood_surface'        => 'account_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_account_login_remember_label',
				'group'      => 'content_surfaces',
				'section'    => 'account',
				'control'    => 'text',
			),
		),
		'account-reset-new-password-label' => array(
			'key'                 => 'account-reset-new-password-label',
			'label'               => 'Account reset new password label',
			'fallback'            => __( 'New password', 'tailwindscore' ),
			'mood_surface'        => 'account_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_account_reset_new_password_label',
				'group'      => 'content_surfaces',
				'section'    => 'account',
				'control'    => 'text',
			),
		),
		'account-reset-confirm-password-label' => array(
			'key'                 => 'account-reset-confirm-password-label',
			'label'               => 'Account reset confirm password label',
			'fallback'            => __( 'Confirm password', 'tailwindscore' ),
			'mood_surface'        => 'account_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_account_reset_confirm_password_label',
				'group'      => 'content_surfaces',
				'section'    => 'account',
				'control'    => 'text',
			),
		),
		'account-reset-submit-label' => array(
			'key'                 => 'account-reset-submit-label',
			'label'               => 'Account reset submit label',
			'fallback'            => __( 'Save new password', 'tailwindscore' ),
			'mood_surface'        => 'account_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_account_reset_submit_label',
				'group'      => 'content_surfaces',
				'section'    => 'account',
				'control'    => 'text',
			),
		),
		'account-view-order-back-label' => array(
			'key'                 => 'account-view-order-back-label',
			'label'               => 'Account view order back label',
			'fallback'            => __( 'Back to orders', 'tailwindscore' ),
			'mood_surface'        => 'account_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_account_view_order_back_label',
				'group'      => 'content_surfaces',
				'section'    => 'account',
				'control'    => 'text',
			),
		),
		'account-address-empty-message' => array(
			'key'                 => 'account-address-empty-message',
			'label'               => 'Account address empty message',
			'fallback'            => __( 'No address saved yet.', 'tailwindscore' ),
			'mood_surface'        => 'account_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_account_address_empty_message',
				'group'      => 'content_surfaces',
				'section'    => 'account',
				'control'    => 'text',
			),
		),
		'account-order-card-meta-format' => array(
			'key'                 => 'account-order-card-meta-format',
			'label'               => 'Account order card meta format',
			'fallback'            => __( '%1$s · %2$s · %3$s', 'tailwindscore' ),
			'mood_surface'        => 'account_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_account_order_card_meta_format',
				'group'      => 'content_surfaces',
				'section'    => 'account',
				'control'    => 'text',
			),
		),
		'account-order-detail-items-heading' => array(
			'key'                 => 'account-order-detail-items-heading',
			'label'               => 'Account order detail items heading',
			'fallback'            => __( 'Items', 'tailwindscore' ),
			'mood_surface'        => 'account_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_account_order_detail_items_heading',
				'group'      => 'content_surfaces',
				'section'    => 'account',
				'control'    => 'text',
			),
		),
		'account-order-detail-quantity-format' => array(
			'key'                 => 'account-order-detail-quantity-format',
			'label'               => 'Account order detail quantity format',
			'fallback'            => __( 'Quantity %d', 'tailwindscore' ),
			'mood_surface'        => 'account_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_account_order_detail_quantity_format',
				'group'      => 'content_surfaces',
				'section'    => 'account',
				'control'    => 'text',
			),
		),
		'account-order-detail-delivery-heading' => array(
			'key'                 => 'account-order-detail-delivery-heading',
			'label'               => 'Account order detail delivery heading',
			'fallback'            => __( 'Delivery', 'tailwindscore' ),
			'mood_surface'        => 'account_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_account_order_detail_delivery_heading',
				'group'      => 'content_surfaces',
				'section'    => 'account',
				'control'    => 'text',
			),
		),
		'account-order-detail-shipping-method-label' => array(
			'key'                 => 'account-order-detail-shipping-method-label',
			'label'               => 'Account order detail shipping method label',
			'fallback'            => __( 'Shipping method', 'tailwindscore' ),
			'mood_surface'        => 'account_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_account_order_detail_shipping_method_label',
				'group'      => 'content_surfaces',
				'section'    => 'account',
				'control'    => 'text',
			),
		),
		'account-order-detail-no-shipping-method' => array(
			'key'                 => 'account-order-detail-no-shipping-method',
			'label'               => 'Account order detail no shipping method',
			'fallback'            => __( 'No shipping required', 'tailwindscore' ),
			'mood_surface'        => 'account_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_account_order_detail_no_shipping_method',
				'group'      => 'content_surfaces',
				'section'    => 'account',
				'control'    => 'text',
			),
		),
		'account-order-detail-shipping-address-label' => array(
			'key'                 => 'account-order-detail-shipping-address-label',
			'label'               => 'Account order detail shipping address label',
			'fallback'            => __( 'Shipping address', 'tailwindscore' ),
			'mood_surface'        => 'account_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_account_order_detail_shipping_address_label',
				'group'      => 'content_surfaces',
				'section'    => 'account',
				'control'    => 'text',
			),
		),
		'account-order-detail-no-shipping-address' => array(
			'key'                 => 'account-order-detail-no-shipping-address',
			'label'               => 'Account order detail no shipping address',
			'fallback'            => __( 'No shipping address provided.', 'tailwindscore' ),
			'mood_surface'        => 'account_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_textarea',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_account_order_detail_no_shipping_address',
				'group'      => 'content_surfaces',
				'section'    => 'account',
				'control'    => 'textarea',
			),
		),
		'account-order-detail-payment-heading' => array(
			'key'                 => 'account-order-detail-payment-heading',
			'label'               => 'Account order detail payment heading',
			'fallback'            => __( 'Payment', 'tailwindscore' ),
			'mood_surface'        => 'account_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_account_order_detail_payment_heading',
				'group'      => 'content_surfaces',
				'section'    => 'account',
				'control'    => 'text',
			),
		),
		'account-order-detail-payment-method-label' => array(
			'key'                 => 'account-order-detail-payment-method-label',
			'label'               => 'Account order detail payment method label',
			'fallback'            => __( 'Method', 'tailwindscore' ),
			'mood_surface'        => 'account_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_account_order_detail_payment_method_label',
				'group'      => 'content_surfaces',
				'section'    => 'account',
				'control'    => 'text',
			),
		),
		'account-order-detail-payment-method-pending' => array(
			'key'                 => 'account-order-detail-payment-method-pending',
			'label'               => 'Account order detail payment method pending',
			'fallback'            => __( 'To be confirmed', 'tailwindscore' ),
			'mood_surface'        => 'account_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_account_order_detail_payment_method_pending',
				'group'      => 'content_surfaces',
				'section'    => 'account',
				'control'    => 'text',
			),
		),
		'account-order-detail-billing-address-label' => array(
			'key'                 => 'account-order-detail-billing-address-label',
			'label'               => 'Account order detail billing address label',
			'fallback'            => __( 'Billing address', 'tailwindscore' ),
			'mood_surface'        => 'account_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_account_order_detail_billing_address_label',
				'group'      => 'content_surfaces',
				'section'    => 'account',
				'control'    => 'text',
			),
		),
		'account-order-detail-no-billing-address' => array(
			'key'                 => 'account-order-detail-no-billing-address',
			'label'               => 'Account order detail no billing address',
			'fallback'            => __( 'No billing address provided.', 'tailwindscore' ),
			'mood_surface'        => 'account_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_textarea',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_account_order_detail_no_billing_address',
				'group'      => 'content_surfaces',
				'section'    => 'account',
				'control'    => 'textarea',
			),
		),
		'reviews-title' => array(
			'key'                 => 'reviews-title',
			'label'               => 'Reviews title',
			'fallback'            => __( 'Customer reviews', 'tailwindscore' ),
			'mood_surface'        => 'support_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_reviews_title',
				'group'      => 'content_surfaces',
				'section'    => 'reviews',
				'control'    => 'text',
			),
		),
		'reviews-intro' => array(
			'key'                 => 'reviews-intro',
			'label'               => 'Reviews intro',
			'fallback'            => __( 'Measured notes from customers, arranged with the same quiet hierarchy as the rest of the product story.', 'tailwindscore' ),
			'mood_surface'        => 'support_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_textarea',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_reviews_intro',
				'group'      => 'content_surfaces',
				'section'    => 'reviews',
				'control'    => 'textarea',
			),
		),
		'reviews-pagination-label' => array(
			'key'                 => 'reviews-pagination-label',
			'label'               => 'Reviews pagination label',
			'fallback'            => __( 'Reviews pagination', 'tailwindscore' ),
			'mood_surface'        => 'support_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_reviews_pagination_label',
				'group'      => 'content_surfaces',
				'section'    => 'reviews',
				'control'    => 'text',
			),
		),
		'reviews-access-eyebrow' => array(
			'key'                 => 'reviews-access-eyebrow',
			'label'               => 'Reviews access eyebrow',
			'fallback'            => __( 'Review access', 'tailwindscore' ),
			'mood_surface'        => 'support_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_reviews_access_eyebrow',
				'group'      => 'content_surfaces',
				'section'    => 'reviews',
				'control'    => 'text',
			),
		),
		'reviews-access-title' => array(
			'key'                 => 'reviews-access-title',
			'label'               => 'Reviews access title',
			'fallback'            => __( 'Purchase required to review', 'tailwindscore' ),
			'mood_surface'        => 'support_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_reviews_access_title',
				'group'      => 'content_surfaces',
				'section'    => 'reviews',
				'control'    => 'text',
			),
		),
		'reviews-access-message' => array(
			'key'                 => 'reviews-access-message',
			'label'               => 'Reviews access message',
			'fallback'            => __( 'Only customers who have purchased this item can leave a review, which keeps the conversation grounded in ownership.', 'tailwindscore' ),
			'mood_surface'        => 'support_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_textarea',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_reviews_access_message',
				'group'      => 'content_surfaces',
				'section'    => 'reviews',
				'control'    => 'textarea',
			),
		),
		'reviews-access-sign-in-label' => array(
			'key'                 => 'reviews-access-sign-in-label',
			'label'               => 'Reviews access sign in label',
			'fallback'            => __( 'Sign in', 'tailwindscore' ),
			'mood_surface'        => 'support_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_reviews_access_sign_in_label',
				'group'      => 'content_surfaces',
				'section'    => 'reviews',
				'control'    => 'text',
			),
		),
		'reviews-form-title' => array(
			'key'                 => 'reviews-form-title',
			'label'               => 'Reviews form title',
			'fallback'            => __( 'Write a review', 'tailwindscore' ),
			'mood_surface'        => 'support_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_reviews_form_title',
				'group'      => 'content_surfaces',
				'section'    => 'reviews',
				'control'    => 'text',
			),
		),
		'reviews-form-title-reply-to' => array(
			'key'                 => 'reviews-form-title-reply-to',
			'label'               => 'Reviews form title reply to',
			'fallback'            => __( 'Reply to %s', 'tailwindscore' ),
			'mood_surface'        => 'support_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_reviews_form_title_reply_to',
				'group'      => 'content_surfaces',
				'section'    => 'reviews',
				'control'    => 'text',
			),
		),
		'reviews-form-intro' => array(
			'key'                 => 'reviews-form-intro',
			'label'               => 'Reviews form intro',
			'fallback'            => __( 'Share a concise note on fit, feel, quality, or everyday use.', 'tailwindscore' ),
			'mood_surface'        => 'support_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_textarea',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_reviews_form_intro',
				'group'      => 'content_surfaces',
				'section'    => 'reviews',
				'control'    => 'textarea',
			),
		),
		'reviews-form-submit-label' => array(
			'key'                 => 'reviews-form-submit-label',
			'label'               => 'Reviews form submit label',
			'fallback'            => __( 'Submit review', 'tailwindscore' ),
			'mood_surface'        => 'support_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_reviews_form_submit_label',
				'group'      => 'content_surfaces',
				'section'    => 'reviews',
				'control'    => 'text',
			),
		),
		'reviews-form-rating-label' => array(
			'key'                 => 'reviews-form-rating-label',
			'label'               => 'Reviews form rating label',
			'fallback'            => __( 'Your rating', 'tailwindscore' ),
			'mood_surface'        => 'support_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_reviews_form_rating_label',
				'group'      => 'content_surfaces',
				'section'    => 'reviews',
				'control'    => 'text',
			),
		),
		'reviews-form-rating-label-optional' => array(
			'key'                 => 'reviews-form-rating-label-optional',
			'label'               => 'Reviews form rating label optional',
			'fallback'            => __( 'Your rating (optional)', 'tailwindscore' ),
			'mood_surface'        => 'support_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_reviews_form_rating_label_optional',
				'group'      => 'content_surfaces',
				'section'    => 'reviews',
				'control'    => 'text',
			),
		),
		'reviews-form-rating-placeholder' => array(
			'key'                 => 'reviews-form-rating-placeholder',
			'label'               => 'Reviews form rating placeholder',
			'fallback'            => __( 'Rate the product', 'tailwindscore' ),
			'mood_surface'        => 'support_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_reviews_form_rating_placeholder',
				'group'      => 'content_surfaces',
				'section'    => 'reviews',
				'control'    => 'text',
			),
		),
		'reviews-form-rating-option-5' => array(
			'key'                 => 'reviews-form-rating-option-5',
			'label'               => 'Reviews form rating option 5',
			'fallback'            => __( 'Perfect', 'tailwindscore' ),
			'mood_surface'        => 'support_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_reviews_form_rating_option_5',
				'group'      => 'content_surfaces',
				'section'    => 'reviews',
				'control'    => 'text',
			),
		),
		'reviews-form-rating-option-4' => array(
			'key'                 => 'reviews-form-rating-option-4',
			'label'               => 'Reviews form rating option 4',
			'fallback'            => __( 'Good', 'tailwindscore' ),
			'mood_surface'        => 'support_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_reviews_form_rating_option_4',
				'group'      => 'content_surfaces',
				'section'    => 'reviews',
				'control'    => 'text',
			),
		),
		'reviews-form-rating-option-3' => array(
			'key'                 => 'reviews-form-rating-option-3',
			'label'               => 'Reviews form rating option 3',
			'fallback'            => __( 'Average', 'tailwindscore' ),
			'mood_surface'        => 'support_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_reviews_form_rating_option_3',
				'group'      => 'content_surfaces',
				'section'    => 'reviews',
				'control'    => 'text',
			),
		),
		'reviews-form-rating-option-2' => array(
			'key'                 => 'reviews-form-rating-option-2',
			'label'               => 'Reviews form rating option 2',
			'fallback'            => __( 'Not that bad', 'tailwindscore' ),
			'mood_surface'        => 'support_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_reviews_form_rating_option_2',
				'group'      => 'content_surfaces',
				'section'    => 'reviews',
				'control'    => 'text',
			),
		),
		'reviews-form-rating-option-1' => array(
			'key'                 => 'reviews-form-rating-option-1',
			'label'               => 'Reviews form rating option 1',
			'fallback'            => __( 'Very poor', 'tailwindscore' ),
			'mood_surface'        => 'support_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_reviews_form_rating_option_1',
				'group'      => 'content_surfaces',
				'section'    => 'reviews',
				'control'    => 'text',
			),
		),
		'reviews-form-review-label' => array(
			'key'                 => 'reviews-form-review-label',
			'label'               => 'Reviews form review label',
			'fallback'            => __( 'Your review', 'tailwindscore' ),
			'mood_surface'        => 'support_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_reviews_form_review_label',
				'group'      => 'content_surfaces',
				'section'    => 'reviews',
				'control'    => 'text',
			),
		),
		'reviews-form-name-label' => array(
			'key'                 => 'reviews-form-name-label',
			'label'               => 'Reviews form name label',
			'fallback'            => __( 'Name', 'tailwindscore' ),
			'mood_surface'        => 'support_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_reviews_form_name_label',
				'group'      => 'content_surfaces',
				'section'    => 'reviews',
				'control'    => 'text',
			),
		),
		'reviews-form-email-label' => array(
			'key'                 => 'reviews-form-email-label',
			'label'               => 'Reviews form email label',
			'fallback'            => __( 'Email', 'tailwindscore' ),
			'mood_surface'        => 'support_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_reviews_form_email_label',
				'group'      => 'content_surfaces',
				'section'    => 'reviews',
				'control'    => 'text',
			),
		),
		'reviews-form-cookies-consent' => array(
			'key'                 => 'reviews-form-cookies-consent',
			'label'               => 'Reviews form cookies consent',
			'fallback'            => __( 'Save my name, email, and website in this browser for the next time I comment.', 'tailwindscore' ),
			'mood_surface'        => 'support_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_textarea',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_reviews_form_cookies_consent',
				'group'      => 'content_surfaces',
				'section'    => 'reviews',
				'control'    => 'textarea',
			),
		),
		'reviews-verified-owner-label' => array(
			'key'                 => 'reviews-verified-owner-label',
			'label'               => 'Reviews verified owner label',
			'fallback'            => __( 'Verified owner', 'tailwindscore' ),
			'mood_surface'        => 'support_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_reviews_verified_owner_label',
				'group'      => 'content_surfaces',
				'section'    => 'reviews',
				'control'    => 'text',
			),
		),
		'search-predictive-empty-message' => array(
			'key'                 => 'search-predictive-empty-message',
			'label'               => 'Search predictive empty message',
			'fallback'            => __( 'Try a broader product name or continue through a collection path.', 'tailwindscore' ),
			'mood_surface'        => 'search_guidance',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_textarea',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_search_predictive_empty_message',
				'group'      => 'content_surfaces',
				'section'    => 'search',
				'control'    => 'textarea',
			),
		),
		'cart-drawer-validation-title' => array(
			'key'                 => 'cart-drawer-validation-title',
			'label'               => 'Cart drawer validation title',
			'fallback'            => __( 'Please review your bag', 'tailwindscore' ),
			'mood_surface'        => 'support_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_cart_drawer_validation_title',
				'group'      => 'content_surfaces',
				'section'    => 'cart',
				'control'    => 'text',
			),
		),
		'cart-drawer-loading-message' => array(
			'key'                 => 'cart-drawer-loading-message',
			'label'               => 'Cart drawer loading message',
			'fallback'            => __( 'Updating bag', 'tailwindscore' ),
			'mood_surface'        => 'support_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_cart_drawer_loading_message',
				'group'      => 'content_surfaces',
				'section'    => 'cart',
				'control'    => 'text',
			),
		),
		'cart-drawer-update-error-message' => array(
			'key'                 => 'cart-drawer-update-error-message',
			'label'               => 'Cart drawer update error message',
			'fallback'            => __( 'We could not update the bag just now. Please try again.', 'tailwindscore' ),
			'mood_surface'        => 'support_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_textarea',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_cart_drawer_update_error_message',
				'group'      => 'content_surfaces',
				'section'    => 'cart',
				'control'    => 'textarea',
			),
		),
		'cart-drawer-item-updated-message' => array(
			'key'                 => 'cart-drawer-item-updated-message',
			'label'               => 'Cart drawer item updated message',
			'fallback'            => __( 'Bag updated', 'tailwindscore' ),
			'mood_surface'        => 'support_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_cart_drawer_item_updated_message',
				'group'      => 'content_surfaces',
				'section'    => 'cart',
				'control'    => 'text',
			),
		),
		'cart-drawer-item-removed-message' => array(
			'key'                 => 'cart-drawer-item-removed-message',
			'label'               => 'Cart drawer item removed message',
			'fallback'            => __( 'Removed from bag', 'tailwindscore' ),
			'mood_surface'        => 'support_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_cart_drawer_item_removed_message',
				'group'      => 'content_surfaces',
				'section'    => 'cart',
				'control'    => 'text',
			),
		),
		'cart-summary-subtotal-label' => array(
			'key'                 => 'cart-summary-subtotal-label',
			'label'               => 'Cart summary subtotal label',
			'fallback'            => __( 'Subtotal', 'tailwindscore' ),
			'mood_surface'        => 'support_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_cart_summary_subtotal_label',
				'group'      => 'content_surfaces',
				'section'    => 'cart',
				'control'    => 'text',
			),
		),
		'cart-summary-note' => array(
			'key'                 => 'cart-summary-note',
			'label'               => 'Cart summary note',
			'fallback'            => __( 'Shipping and taxes calculated at checkout.', 'tailwindscore' ),
			'mood_surface'        => 'support_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_textarea',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_cart_summary_note',
				'group'      => 'content_surfaces',
				'section'    => 'cart',
				'control'    => 'textarea',
			),
		),
		'cart-summary-checkout-label' => array(
			'key'                 => 'cart-summary-checkout-label',
			'label'               => 'Cart summary checkout label',
			'fallback'            => __( 'Checkout', 'tailwindscore' ),
			'mood_surface'        => 'support_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_cart_summary_checkout_label',
				'group'      => 'content_surfaces',
				'section'    => 'cart',
				'control'    => 'text',
			),
		),
		'cart-summary-view-cart-label' => array(
			'key'                 => 'cart-summary-view-cart-label',
			'label'               => 'Cart summary view cart label',
			'fallback'            => __( 'View cart', 'tailwindscore' ),
			'mood_surface'        => 'support_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_cart_summary_view_cart_label',
				'group'      => 'content_surfaces',
				'section'    => 'cart',
				'control'    => 'text',
			),
		),
		'cart-line-item-subtotal-label' => array(
			'key'                 => 'cart-line-item-subtotal-label',
			'label'               => 'Cart line item subtotal label',
			'fallback'            => __( 'Subtotal', 'tailwindscore' ),
			'mood_surface'        => 'support_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_cart_line_item_subtotal_label',
				'group'      => 'content_surfaces',
				'section'    => 'cart',
				'control'    => 'text',
			),
		),
		'add-to-cart-validation-title' => array(
			'key'                 => 'add-to-cart-validation-title',
			'label'               => 'Add to cart validation title',
			'fallback'            => __( 'Please review this selection', 'tailwindscore' ),
			'mood_surface'        => 'support_messaging',
			'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
			'translation_support' => true,
			'ssr_output'          => 'tailwindscore_content_surface_value',
			'customization_entry' => array(
				'transport'  => 'theme_mod',
				'setting_id' => 'ts_surface_add_to_cart_validation_title',
				'group'      => 'content_surfaces',
				'section'    => 'cart',
				'control'    => 'text',
			),
		),
	);

	$empty_states = array(
		'cart'                   => array(
			'eyebrow' => __( 'Your bag', 'tailwindscore' ),
			'title'   => __( 'Your cart is empty', 'tailwindscore' ),
			'message' => __( 'Begin with a considered selection and return here when you are ready to check out.', 'tailwindscore' ),
		),
		'checkout-unavailable'   => array(
			'eyebrow' => __( 'Purchase flow', 'tailwindscore' ),
			'title'   => __( 'Checkout is not available yet', 'tailwindscore' ),
			'message' => __( 'Sign in or return to your bag to continue with a secure purchase.', 'tailwindscore' ),
		),
		'orders'                 => array(
			'eyebrow' => __( 'Order history', 'tailwindscore' ),
			'title'   => __( 'No orders yet', 'tailwindscore' ),
			'message' => __( 'When an order is placed, its progress and details will appear here in a calm, easy-to-review timeline.', 'tailwindscore' ),
		),
		'downloads'              => array(
			'eyebrow' => __( 'Digital purchases', 'tailwindscore' ),
			'title'   => __( 'No downloads yet', 'tailwindscore' ),
			'message' => __( 'Digital purchases will appear here as soon as they are ready to access.', 'tailwindscore' ),
		),
		'addresses'              => array(
			'eyebrow' => __( 'Address book', 'tailwindscore' ),
			'title'   => __( 'No address saved', 'tailwindscore' ),
			'message' => __( 'Add a billing or shipping address to make your next checkout feel faster and more considered.', 'tailwindscore' ),
		),
		'logged-out'             => array(
			'eyebrow' => __( 'Customer account', 'tailwindscore' ),
			'title'   => __( 'Sign in to continue', 'tailwindscore' ),
			'message' => __( 'Access your orders, saved details, and post-purchase history from one premium account surface.', 'tailwindscore' ),
		),
		'search-results'         => array(
			'eyebrow' => __( 'Search', 'tailwindscore' ),
			'title'   => __( 'No matching pieces found', 'tailwindscore' ),
			'message' => __( 'Try a broader product name or continue through a collection path.', 'tailwindscore' ),
		),
		'search-unavailable'     => array(
			'eyebrow' => __( 'Search', 'tailwindscore' ),
			'title'   => __( 'Search is unavailable for the moment', 'tailwindscore' ),
			'message' => __( 'Please try again in a moment, or continue by browsing the collection directly.', 'tailwindscore' ),
		),
		'archive-empty'          => array(
			'eyebrow' => __( 'Collection', 'tailwindscore' ),
			'title'   => __( 'Nothing is available here just yet', 'tailwindscore' ),
			'message' => __( 'Continue through another collection path to keep browsing the full edit.', 'tailwindscore' ),
		),
		'archive-category-empty' => array(
			'eyebrow' => __( 'Collection', 'tailwindscore' ),
			'title'   => __( 'This collection is currently quiet', 'tailwindscore' ),
			'message' => __( 'Please return to the wider collection and continue browsing from there.', 'tailwindscore' ),
		),
		'archive-filtered-empty' => array(
			'eyebrow' => __( 'Filtered view', 'tailwindscore' ),
			'title'   => __( 'No pieces match this selection', 'tailwindscore' ),
			'message' => __( 'Clear one or two filters to restore a broader collection view.', 'tailwindscore' ),
		),
		'archive-out-of-stock'   => array(
			'eyebrow' => __( 'Availability', 'tailwindscore' ),
			'title'   => __( 'Nothing in this view is currently available', 'tailwindscore' ),
			'message' => __( 'Return to the full collection to continue browsing what is available now.', 'tailwindscore' ),
		),
		'reviews'                => array(
			'eyebrow' => __( 'Customer reviews', 'tailwindscore' ),
			'title'   => __( 'No reviews yet', 'tailwindscore' ),
			'message' => __( 'The first review will appear here once a customer has spent time with this piece.', 'tailwindscore' ),
		),
		'variation-unavailable'  => array(
			'eyebrow' => __( 'Variation selection', 'tailwindscore' ),
			'title'   => __( 'This option is currently unavailable', 'tailwindscore' ),
			'message' => __( 'Choose another combination to continue with an available configuration.', 'tailwindscore' ),
		),
		'out-of-stock'           => array(
			'eyebrow' => __( 'Availability', 'tailwindscore' ),
			'title'   => __( 'Currently out of stock', 'tailwindscore' ),
			'message' => __( 'This item is not available to purchase at the moment. Check back soon for availability.', 'tailwindscore' ),
		),
	);

	foreach ( $empty_states as $context => $copy ) {
		foreach ( $copy as $slot => $fallback ) {
			$key                = sprintf( 'empty-state-%s-%s', $context, $slot );
			$registry[ $key ]   = array(
				'key'                 => $key,
				'label'               => sprintf( 'Empty state %s %s', $context, $slot ),
				'fallback'            => $fallback,
				'mood_surface'        => 'empty_states',
				'sanitizer'           => 'tailwindscore_content_surface_sanitize_text',
				'translation_support' => true,
				'ssr_output'          => 'tailwindscore_feedback_empty_state_copy',
				'customization_entry' => array(
					'transport'  => 'theme_mod',
					'setting_id' => 'ts_surface_' . str_replace( '-', '_', $key ),
					'group'      => 'content_surfaces',
					'section'    => 'empty_states',
					'control'    => 'text',
				),
			);
		}
	}

	/**
	 * Filter registry definitions.
	 *
	 * @param array<string, array<string, mixed>> $registry Surface registry.
	 */
	$registry = apply_filters( 'tailwindscore/content_surfaces/registry', $registry );

	return $registry;
}

/**
 * Fetch a single surface definition.
 *
 * @return array<string, mixed>|null
 */
function tailwindscore_content_surface_definition( string $key ): ?array {
	$registry = tailwindscore_content_surface_registry();
	$key      = sanitize_key( $key );

	return isset( $registry[ $key ] ) && is_array( $registry[ $key ] ) ? $registry[ $key ] : null;
}

/**
 * Resolve the current value for a governed surface.
 *
 * @return mixed
 */
function tailwindscore_content_surface_value( string $key ) {
	$surface = tailwindscore_content_surface_definition( $key );

	if ( ! is_array( $surface ) ) {
		return null;
	}

	$fallback  = $surface['fallback'] ?? '';
	$sanitizer = $surface['sanitizer'] ?? null;
	$value     = null;
	$entry     = isset( $surface['customization_entry'] ) && is_array( $surface['customization_entry'] ) ? $surface['customization_entry'] : array();

	if ( isset( $entry['setting_id'], $entry['transport'] ) ) {
		$setting_id = sanitize_key( (string) $entry['setting_id'] );
		$transport  = sanitize_key( (string) $entry['transport'] );

		if ( '' !== $setting_id ) {
			if ( 'theme_mod' === $transport ) {
				$value = get_theme_mod( $setting_id, null );
			} elseif ( 'option' === $transport ) {
				$value = get_option( $setting_id, null );
			}
		}
	}

	if ( function_exists( 'tailwindscore_content_mood_surface_fallback' ) ) {
		$fallback = tailwindscore_content_mood_surface_fallback( $key, $fallback );
	}

	if ( is_callable( $sanitizer ) ) {
		$value    = null === $value ? null : call_user_func( $sanitizer, $value );
		$fallback = call_user_func( $sanitizer, $fallback );
	}

	if ( null === $value || tailwindscore_content_surface_is_empty( $value ) ) {
		$value = $fallback;
	}

	/**
	 * Filter a resolved content surface value.
	 *
	 * @param mixed                $value   Surface value.
	 * @param string               $key     Surface key.
	 * @param array<string, mixed> $surface Surface definition.
	 */
	return apply_filters( 'tailwindscore/content_surfaces/value', $value, $key, $surface );
}

/**
 * Resolve a governed surface value as string.
 */
function tailwindscore_content_surface_text( string $key, string $default = '' ): string {
	$value = tailwindscore_content_surface_value( $key );

	return is_string( $value ) && '' !== trim( $value ) ? $value : $default;
}
