/**
 * Register TS modules (side-effect imports).
 */
import { registerModule } from '../bootstrap-registry';
import { mount as mountCommerceQuantity } from './commerce/quantity';
import { mount as mountCommerceAddToCart } from './commerce/add-to-cart';
import { mount as mountCommerceNotices } from './commerce/notices';
import { mount as mountFeedbackRuntime } from './feedback';
import { mount as mountCheckoutFeedback } from './checkout-feedback';
import { mount as mountCheckoutLoading } from './checkout/checkout-loading';
import { mount as mountCheckoutSummary } from './checkout/checkout-summary';
import { mount as mountCheckoutPayment } from './checkout/checkout-payment';
import { mount as mountCheckoutFocus } from './checkout/checkout-focus';
import { mount as mountArchiveRuntime } from './archive';
import { mount as mountProductGallery } from './gallery';
import { mount as mountVariationRuntime } from './variations';
import { mount as mountMobileDrawer } from './site-shell/mobile-drawer';
import { mount as mountStickyHeader } from './site-shell/sticky-header';
import { mount as mountNavigationFocus } from './site-shell/navigation-focus';
import { mount as mountSearchSurface } from './search/search-surface';
import { mount as mountPredictiveSearch } from './search/predictive-search';
import { mount as mountSearchFocus } from './search/search-focus';
import { mount as mountCartDrawer } from './cart-surface/cart-drawer';
import { mount as mountCartFocus } from './cart-surface/cart-focus';
import { mount as mountAccountNavigation } from './account/account-navigation';
import { mount as mountOrderToggle } from './account/order-toggle';
import { mount as mountAccountFocus } from './account/account-focus';

registerModule('commerce-quantity', mountCommerceQuantity);
registerModule('commerce-add-to-cart', mountCommerceAddToCart);
registerModule('commerce-notices', mountCommerceNotices);
registerModule('feedback-runtime', mountFeedbackRuntime);
registerModule('checkout-feedback', mountCheckoutFeedback);
registerModule('checkout-loading', mountCheckoutLoading);
registerModule('checkout-summary', mountCheckoutSummary);
registerModule('checkout-payment', mountCheckoutPayment);
registerModule('checkout-focus', mountCheckoutFocus);
registerModule('tailwindscore-archive-runtime', mountArchiveRuntime);
registerModule('tailwindscore-variation-runtime', mountVariationRuntime);
registerModule('tailwindscore-product-gallery', mountProductGallery);
registerModule('mobile-drawer', mountMobileDrawer);
registerModule('sticky-header', mountStickyHeader);
registerModule('navigation-focus', mountNavigationFocus);
registerModule('search-surface', mountSearchSurface);
registerModule('predictive-search', mountPredictiveSearch);
registerModule('search-focus', mountSearchFocus);
registerModule('cart-drawer', mountCartDrawer);
registerModule('cart-focus', mountCartFocus);
registerModule('account-navigation', mountAccountNavigation);
registerModule('order-toggle', mountOrderToggle);
registerModule('account-focus', mountAccountFocus);
